services:
  # MongoDB services
  mongo_db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - portfolio:/data/db
  
  # Node API service
  api:
    build: ./packages/server
    ports:
      - "4000:4000"
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://mongo_db:27017/portfolio
      PORT: 4000
      PORTFOLIO_JWT_SECRET: jwtPrivatKey
      NODE_ENV: development
    depends_on:
      - mongo_db

  web:
    build: ./packages/client
    ports:
      - "80:80"
    volumes:
      - ./packages/client:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://54.191.32.75:4000/api
    depends_on:
      - api

volumes:
  portfolio: